### PR TITLE
Net 8

### PR DESCRIPTION
**Pull request by migueBarrera**
I have updated the maui project and the sample to net8. 

I have updated ComunityToolkit too from 3.3.1 to 5.3.0

All the functional tests I have done work fine but in the UI we have a style bug with the Border.

Screenshot_2023-09-04-12-33-20-993_com companyname xcalendarmauisample

I create this PR in draft mode waiting for net 8 to be officially released and waiting for the Border to be visually corrected.

### CODE REVIEW

**Comment by ME-MarvinE** [comment]
The border might be like that because the HeightRequest of the DayView is slightly too small now due to some change between the .NET versions. Maybe it should be increased?

**Comment by migueBarrera** [comment]
Hi @ME-MarvinE . I have update to last changes and stable net8. 
In my tests, in debug, the calendar loads 1-2 aprox seconds faster. 
We have the same issue with border and i do not found the issue. Can you review ?

**Comment by ME-MarvinE** [comment]
The border is like that because the control does not have enough width/height. On my devices it looks fine. Developers should be able to change the WidthRequest/HeightRequest as they need. Otherwise, I think this is ready to merge.

**Comment by migueBarrera** [comment]
Nice!! Merge this pr please and thank you!!!.

**Pull request merged**
